import "./globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header, Footer, Search } from "../components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "GadgetGrid - Your Gadget",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
  signin,
}: {
  children: React.ReactNode;
  signin?: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Search />
        {signin}
        {children}
        <Footer />
      </body>
    </html>
  );
}
